from . import (
    andalucia,
    aragon,
    asturias,
    baleares,
    canarias,
    cantabria,
    castilla_la_mancha,
    castilla_y_leon,
    cataluna,
    ceuta,
    extremadura,
    galicia,
    la_rioja,
    madrid,
    melilla,
    murcia,
    navarra,
    pais_vasco,
    valencia,
)
from ._common import PARSE_FIXES

__all__ = [
    "PARSE_FIXES",
    "andalucia",
    "aragon",
    "asturias",
    "baleares",
    "canarias",
    "cantabria",
    "castilla_la_mancha",
    "castilla_y_leon",
    "cataluna",
    "ceuta",
    "extremadura",
    "galicia",
    "la_rioja",
    "madrid",
    "melilla",
    "murcia",
    "navarra",
    "pais_vasco",
    "valencia",
]
